<a href="https://colab.research.google.com/github/g-r-a-e-m-e/essential-math-for-data-science/blob/main/chapter_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 04

## Linear Algebra

### What is a Vector?

In [1]:
# Example 4-1. Declaring a vector in Python using a list
v = [3, 2]
print(v)

[3, 2]


In [2]:
# Example 4-2. Declaring a vector in Python using NumPy

import numpy as np
v = np.array([3, 2])
print(v)

[3 2]


In [3]:
# Example 4-3. Declaring a three-dimensional vector in Python using NumPy

import numpy as np
v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [4]:
# Example 4-4. Declaring a five-dimensional vector in Python using NumPy

import numpy as np
v = np.array([6, 1, 5, 8 ,3])
print(v)

[6 1 5 8 3]


#### Adding and Combining Vectors

In [5]:
# Example 4-5. Adding two vectors in Python using NumPy

from numpy import array

v = array([3, 2])
w = array([2, -1])

# sum the vectors
v_plus_w = v + w

# display the summed vector
print(v_plus_w)

[5 1]


#### Scaling Vectors

In [6]:
# Example 4-6. Scaling a number in Python using NumPy

from numpy import array
v = array([3, 1])

# scale the vector
scaled_v = 2.0 * v

# display the scaled vector
print(scaled_v)

[6. 2.]


### Linear Transformations
#### Matrix Vector Multiplication

In [7]:
# Example 4-7. Matrix vector multiplication in NumPy

from numpy import array

# compose basis matrix with i-hat and j-hat
basis = array([[3, 0],
              [0, 2]])

# declare vector v
v = array([1, 1])

# create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[3 2]


In [8]:
# Example 4-8. Separating the basis vectors and applying them as a transformation

from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 0])
j_hat = array([0, 3])

# Compose basis matrix using i-hat and j-hat; transpose rows to columns
basis = array([i_hat, j_hat]).transpose()

# Declare vector v
v = array([1, 1])

# Create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[2 3]


In [9]:
# Example 4-9. Transforming a vector using NumPy

from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 0])
j_hat = array([0, 3])

# Compose basis matrix using i-hat and j-hat; transpose rows to columns
basis = array([i_hat, j_hat]).transpose()

# Declare vector v
v = array([2, 1])

# Create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[4 3]


In [10]:
# Example 4-10. A more complicated transformation

from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 3])
j_hat = array([2, -1])

# Compose basis matrix using i-hat and j-hat; transpose rows to columns
basis = array([i_hat, j_hat]).transpose()

# Declare vector v
v = array([2, 1])

# Create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[6 5]


### Matrix Multiplication

In [11]:
# Example 4-11. Combining two transformations

import numpy as np

# Transformation 1
i_hat_1 = np.array([0, 1])
j_hat_1 = np.array([-1, 0])
transform_1 = np.array([i_hat_1, j_hat_1]).transpose()

# Transformation 2
i_hat_2 = np.array([1, 0])
j_hat_2 = np.array([1, 1])
transform_2 = np.array([i_hat_2, j_hat_2]).transpose()

# Combine transformations
combined = np.matmul(transform_2, transform_1)

print(f"Combined Matrix:\n{combined}")

v = array([1, 2])

print(combined.dot(v))

Combined Matrix:
[[ 1 -1]
 [ 1  0]]
[-1  1]


In [12]:
# Example 4-12. Applying the transformations in reverse

import numpy as np

# Transformation 1
i_hat_1 = np.array([0, 1])
j_hat_1 = np.array([-1, 0])
transform_1 = np.array([i_hat_1, j_hat_1]).transpose()

# Transformation 2
i_hat_2 = np.array([1, 0])
j_hat_2 = np.array([1, 1])
transform_2 = np.array([i_hat_2, j_hat_2]).transpose()

# Combine transformations
combined = np.matmul(transform_1, transform_2)

print(f"Combined Matrix:\n{combined}")

v = array([1, 2])

print(combined.dot(v))

Combined Matrix:
[[ 0 -1]
 [ 1  1]]
[-2  3]


#### Determinants

In [13]:
# Example 4-13. Calculating a determinant

import numpy as np
from numpy.linalg import det

i_hat = np.array([3, 0])
j_hat = np.array([0, 2])

basis = np.array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

6.0


In [14]:
# Example 4-14. A determinant for a shear

import numpy as np
from numpy.linalg import det

i_hat = np.array([1, 0])
j_hat = np.array([1, 1])

basis = np.array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

1.0


In [15]:
# Example 4-15. A negative determinant

import numpy as np
from numpy.linalg import det

i_hat = np.array([-2, 1])
j_hat = np.array([1, 2])

basis = np.array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

-5.000000000000001


In [16]:
# Example 4-16. A determinant of zero

import numpy as np
from numpy.linalg import det

i_hat = np.array([-2, 1])
j_hat = np.array([3, -1.5])

basis = np.array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

0.0


#### Systems of Equations and Inverse Matrices

In [17]:
# Example 4-17. Using SymPy to study the inverse and identity matrix

from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

# dot product between A and its inverse will produce the identity function
inverse = A.inv()
identity = inverse * A

print(f"INVERSE: {inverse}")
print(f"IDENTITY: {identity}")

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [18]:
# Example 4-18. Using NumPy to solve a system of equations

import numpy as np
from numpy.linalg import inv

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = array([
    44,
    56,
    72
])

X = inv(A).dot(B)

print(X)

[ 2. 34. -8.]


In [19]:
# Example 4-19. Using SymPy to solve a system of equations

from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = Matrix([
    44,
    56,
    72
])

X = A.inv() * B

print(X)

Matrix([[2], [34], [-8]])


#### Eigenvectors and Eigenvalues

In [20]:
# Example 4-20. Performing eigendecomposition in NumPy

import numpy as np
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvalues, eigenvectors = eig(A)

print(f"EIGENVALUES: \n{eigenvalues}")
print(f"EIGENVECTORS: \n{eigenvectors}")

EIGENVALUES: 
[-0.46410162  6.46410162]
EIGENVECTORS: 
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [21]:
# Example 4-21. Decomposing and recomposing a matrix in NumPy

import numpy as np
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvalues, eigenvectors = eig(A)

print(f"EIGENVALUES: \n{eigenvalues}")
print(f"EIGENVECTORS: \n{eigenvectors}")

Q = eigenvectors
R = inv(Q)

L = np.diag(eigenvalues)
B = Q @ L @ R

print(f"REBUILD MATRIX: \n {B}")

EIGENVALUES: 
[-0.46410162  6.46410162]
EIGENVECTORS: 
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]
REBUILD MATRIX: 
 [[1. 2.]
 [4. 5.]]


## Conclusion

### Exercises

#### 1. Vector $\vec{v}$ has a value of $[1,2]$ but then a transformation happens. $\hat{i}$ lands at $[2,0]$ and $\hat{j}$ lands at $[0,1.5]$. Where does $\vec{v}$ land?

In [22]:
import numpy as np

v_1 = np.array([1, 2])

i_hat = np.array([2, 0])
j_hat = np.array([0, 1.5])

basis = np.array([i_hat, j_hat])

v_2 = basis.dot(v_1)

print(v_2)

[2. 3.]


####2. Vector $\vec{v}$ has a value of $[1,2]$ but then a transformation happens. $\hat{i}$ lands at $[-2,1]$ and $\hat{j}$ lands at $[1,-2]$. Where does $\vec{v}$ land?

In [23]:
import numpy as np

v_1 = np.array([1, 2])

i_hat = np.array([-2, 1])
j_hat = np.array([1, -2])

basis = np.array([i_hat, j_hat])

v_2 = basis.dot(v_1)

print(v_2)

[ 0 -3]


#### 3. A transformation $\hat{i}$ lands at $[1,0]$ and $\hat{j}$ lands at $[2,2]$. What is the determinant of this transformation?

In [24]:
import numpy as np
from numpy.linalg import det

i_hat = np.array([1, 0])
j_hat = np.array([2, 2])

basis = np.array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

2.0


#### 4. Can two or more linear transformations be done in a single linear transformation? Why or why not?

Yes. A linear transformation can contain multiple transformations of the types scale, rotate, shear, and inversion.

#### 5. Solve the system of equations for $x$, $y$, and $z$:

$\mbox{3x + 1y + 0z = 54}$

$\mbox{2x + 4y + 1z = 12}$

$\mbox{3x + 1y + 8z = 6}$

In [25]:
import numpy as np
from numpy.linalg import inv

A = np.array([
    [3, 1, 0],
    [2, 4, 1],
    [3, 1, 8]
])

B = np.array([
    54,
    12,
    6
])

X = inv(A).dot(B)

print(X)

[19.8 -5.4 -6. ]


#### 6. Is the following matrix linearly dependent? Why or why not?

$\begin{bmatrix}
  2 & 1 \\
  6 & 3
\end{bmatrix}$


In [26]:
import numpy as np
from numpy.linalg import det

i_hat = np.array([2, 1])
j_hat = np.array([6, 3])

basis = np.array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(f"Yes, this matrix is linearly dependent because the determinant is {determinant}.")

Yes, this matrix is linearly dependent because the determinant is 0.0.
