<a href="https://colab.research.google.com/github/g-r-a-e-m-e/essential-math-for-data-science/blob/main/chapter_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 04

## Linear Algebra

### What is a Vector?

In [1]:
# Example 4-1. Declaring a vector in Python using a list
v = [3, 2]
print(v)

[3, 2]


In [2]:
# Example 4-2. Declaring a vector in Python using NumPy

import numpy as np
v = np.array([3, 2])
print(v)

[3 2]


In [3]:
# Example 4-3. Declaring a three-dimensional vector in Python using NumPy

import numpy as np
v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [4]:
# Example 4-4. Declaring a five-dimensional vector in Python using NumPy

import numpy as np
v = np.array([6, 1, 5, 8 ,3])
print(v)

[6 1 5 8 3]


#### Adding and Combining Vectors

In [5]:
# Example 4-5. Adding two vectors in Python using NumPy

from numpy import array

v = array([3, 2])
w = array([2, -1])

# sum the vectors
v_plus_w = v + w

# display the summed vector
print(v_plus_w)

[5 1]


#### Scaling Vectors

In [6]:
# Example 4-6. Scaling a number in Python using NumPy

from numpy import array
v = array([3, 1])

# scale the vector
scaled_v = 2.0 * v

# display the scaled vector
print(scaled_v)

[6. 2.]


### Linear Transformations
#### Matrix Vector Multiplication

In [7]:
# Example 4-7. Matrix vector multiplication in NumPy

from numpy import array

# compose basis matrix with i-hat and j-hat
basis = array([[3, 0],
              [0, 2]])

# declare vector v
v = array([1, 1])

# create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[3 2]


In [8]:
# Example 4-8. Separating the basis vectors and applying them as a transformation

from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 0])
j_hat = array([0, 3])

# Compose basis matrix using i-hat and j-hat; transpose rows to columns
basis = array([i_hat, j_hat]).transpose()

# Declare vector v
v = array([1, 1])

# Create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[2 3]


In [9]:
# Example 4-9. Transforming a vector using NumPy

from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 0])
j_hat = array([0, 3])

# Compose basis matrix using i-hat and j-hat; transpose rows to columns
basis = array([i_hat, j_hat]).transpose()

# Declare vector v
v = array([2, 1])

# Create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[4 3]


In [10]:
# Example 4-10. A more complicated transformation

from numpy import array

# Declare i-hat and j-hat
i_hat = array([2, 3])
j_hat = array([2, -1])

# Compose basis matrix using i-hat and j-hat; transpose rows to columns
basis = array([i_hat, j_hat]).transpose()

# Declare vector v
v = array([2, 1])

# Create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[6 5]


### Matrix Multiplication

In [11]:
# Example 4-11. Combining two transformations

import numpy as np

# Transformation 1
i_hat_1 = np.array([0, 1])
j_hat_1 = np.array([-1, 0])
transform_1 = np.array([i_hat_1, j_hat_1]).transpose()

# Transformation 2
i_hat_2 = np.array([1, 0])
j_hat_2 = np.array([1, 1])
transform_2 = np.array([i_hat_2, j_hat_2]).transpose()

# Combine transformations
combined = np.matmul(transform_2, transform_1)

print(f"Combined Matrix:\n{combined}")

Combined Matrix:
[[ 1 -1]
 [ 1  0]]
